#Simple docker-compose.yml taking from https://github.com/jenkinsci/docker#docker-compose-with-jenkins


services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:	
      - /home/sharker3312/Documentos/Devops-Projects/Devops-Projects/CD_pipeline_for_an_app/jenkins_home:/var/jenkins_home
      #- jenkins_home:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent
volumes:
  jenkins_home:
